# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen.xci
# IP: The module: 'tx_axis_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen/tx_axis_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_axis_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_axis_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen.xci
# IP: The module: 'tx_axis_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen/tx_axis_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_axis_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/srio_test/srio_test/srio_test.srcs/sources_1/ip/tx_axis_gen/tx_axis_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_axis_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
