# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/srio_test/srio_test/top.xdc

# IP: ip/srio_gen2_0/srio_gen2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==srio_gen2_0 || ORIG_REF_NAME==srio_gen2_0}]
